import { Inter } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: 'task',
  description: 'Generated by create next app',
  icons:{
    icon:['/images/Untitled.jpg'],
    apple:['/'],
    shortcut:['/']
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
